// <auto-generated />
namespace DivishRam_PassionProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cartable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cartable));
        
        string IMigrationMetadata.Id
        {
            get { return "202202280034095_cartable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
